services:
  registry-server:
    image: registry:latest
    restart: always
    ports:
      - "192.168.146.133:5000:5000"
    volumes:
      # Mount the password file
      - ./registry/registry.password:/auth/registry.password
      # Mount the data dir
      - ./registry/data:/var/lib/registry
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
      REGISTRY_STORAGE_DELETE_ENABLED: "true"  # Enable image deletes
    container_name: registry-server

  registry-ui:
    image: joxit/docker-registry-ui:main
    restart: always
    ports:
      - "9090:80"
    environment:
      - SINGLE_REGISTRY=true
      - REGISTRY_TITLE=Private Docker Registry UI
      - DELETE_IMAGES=true
      - SHOW_CONTENT_DIGEST=true
      - NGINX_PROXY_PASS_URL=http://registry-server:5000
      - SHOW_CATALOG_NB_TAGS=true
      - TAGLIST_PAGE_SIZE=100
      - REGISTRY_SECURED=false  # For basic setups; add auth in production!
    container_name: registry-ui
    depends_on:
      - registry-server
